title: Lift Her Wealth | Dec 1-2, 2020 | Virtual Summit | Empowering womxn & demystifying money
description: >-
  A virtual summit for women who are looking to demystify the complicated world of money. Connect with and learn from women as they speak about stock investing, salary negotiation, building a budget, setting professional and financial goals, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_handle: https://twitter.com/liftherwealth

sass:
  style: compressed
  sass_dir: _scss
